### ISSUE TITLE
The PHP Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by saidbakr** [HvyIndustries/crane#305] opened 2017-04-23 20:50 UTC
Platform : win32
VSCode Version : 1.11.2
Crane Version : 0.3.6
---

_The PHP language server indexing_

```
...
[Info  - 10:46:36 PM] Restored league/flysystem:1.0.37 from cache
[Info  - 10:46:36 PM] Restored mockery/mockery:0.9.9 from cache
[Info  - 10:46:36 PM] Indexing monolog/monolog:1.22.1 for definitions and static references
Parsing file:///c:/Users/Said/Desktop/Project/laravel/factory/vendor/monolog/monolog/src/Monolog/ErrorHandler.php
[Error - 10:46:36 PM] Connection to server got closed. Server will not be restarted.
```

I have tried to execlude indexing at this path:
```
"files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    "**/monolog/monolog": true
  }
```
But nothing, it try to index in that path again.

**Comment by ichiriac** [comment] 2017-04-24 10:02
Hi @saidbakr,

Your log output seems to not match with our output. Do you use another plugin for PHP ?

**Comment by nevadascout** [comment] 2017-05-25 10:55
Closing as this is not a bug with Crane.

**Closed by nevadascout** 2017-05-25 10:55 UTC
