### ISSUE TITLE
Getting "Cannot read property 'namespaceUsings' of null" in the output window

### ISSUE THREAD

**Issue by tiger2380** [HvyIndustries/crane#276] opened 2017-03-21 16:08 UTC
Platform : win32
VSCode Version : 1.10.2
Crane Version : 0.3.4
---

Getting this error message in the output window: "Request textDocument/definition failed. Message: Request textDocument/definition failed with message: Cannot read property 'namespaceUsings' of null Code: -32603"

I have a static PHP method in my script. When I tried to go to the declaration by holding down ctrl and mouseover the method's name (don't have to click), it will gives that error message in the output window.

Let me know if you need more information.
Thanks.

**Comment by ichiriac** [comment] 2017-03-21 20:07
I can't reproduce the error, but it fails to retrieve definition :

![image](https://cloud.githubusercontent.com/assets/173203/24168401/574d99be-0e7a-11e7-8b49-46ecef1cb2f3.png)

Could you provide a snippet in order to reproduce the error.

**Comment by nevadascout** [comment] 2017-03-23 21:06
Released in v0.3.5

**Closed by nevadascout** 2017-03-23 21:06 UTC
Labels: bug, investigate
