### ISSUE TITLE
Not working with Yii 2.x.x version

### ISSUE THREAD

**Issue by brussens** [HvyIndustries/crane#128] opened 2016-07-15 03:41 UTC
Good time!
Thank you for your extension!
But, unfortunately, it can not work with Yii 2.x.x. Installation Yii takes place via Composer, if it is important. I hope for further support for the emergence of Yii.
P.S.: Sorry for the bad English :)

**Comment by nevadascout** [comment] 2017-03-04 01:18
Duplicate of #148

**Closed by nevadascout** 2017-03-04 01:18 UTC
Labels: bug, php framework
