### ISSUE TITLE
Not indexing WordPress files

### ISSUE THREAD

**Issue by hadi77ir** [HvyIndustries/crane#132] opened 2016-07-29 23:55 UTC
It is not WordPress-compliant, for example when we are developing plugins or making themes its dictionary doesn't have any of WordPress functions.

**Comment by TheColorRed** [comment] 2016-07-31 20:01
I don't know much about wordpress, but do any of these files have HTML in them?

**Comment by nevadascout** [comment] 2016-08-02 16:29
If there are top level (global) functions declared in other files, they won't be suggested in the file that you're working in. This is being changed in a future release.

**Comment by tanc** [comment] 2016-08-27 10:42
This appears to be the case for Drupal 7 too. Drupal 7 uses procedural code and it seems as if this extension doesn't pick it up for suggestions in the current file.

**Comment by nevadascout** [comment] 2017-03-04 01:21
Duplicate of #148 (added Drupal to the list too)

**Closed by nevadascout** 2017-03-04 01:21 UTC
Labels: improvement, more info needed
