### ISSUE TITLE
null coalesce not recognized and marked as syntax error

### ISSUE THREAD

**Issue by thomasmoors** [HvyIndustries/crane#179] opened 2016-10-21 12:38 UTC
When using the null coalesce operator, it will say: syntax error, unexpected ' ?'.
for example:

`$url_operator = $matches[1][0] ?? false;`

**Comment by nevadascout** [comment] 2016-10-21 13:56
Thanks for reporting this!

@ichiriac looks like more PHP7 functionality that we need to add

**Comment by TheColorRed** [comment] 2016-10-21 23:41
What version of PHP is installed on your computer? If I am not mistaken vscode uses the linter that is installed on your computer.  I don't think that this is a crane issue.

**Comment by ichiriac** [comment] 2016-10-22 09:56
@nevadascoot I plan to do it next week, just need to find some time. + fix line/column location bug

The harder part for the release will be  to increase test coverage on lexer (btw actually lexer on master has many fixes vs release 10)

**Comment by nevadascout** [comment] 2016-10-22 09:57
You're awesome @ichiriac 😄

**Comment by thomasmoors** [comment] 2016-10-24 11:57
@TheColorRed both XAMPP and MAMP. If it uses path vars as suspected it will be XAMPP running 5,6 by default, so you could be right.

**Comment by TheColorRed** [comment] 2016-10-24 18:07
@thomasmoors If you have php 7 installed, you can setup the path in your editor settings:

```json
{
    "php.validate.executablePath": "c:\\php\\folder"
}
```

**Comment by TheColorRed** [comment] 2016-10-28 21:00
@thomasmoors I assume this fixed your issue? If so, @nevadascout I think this could be closed.

**Comment by nevadascout** [comment] 2016-10-28 22:04
Closing. We can re-open if the issue is not resolved

**Closed by nevadascout** 2016-10-28 22:04 UTC
Labels: bug, php-parser
