### ISSUE TITLE
Codeigniter support?

### ISSUE THREAD

**Issue by RazaLabs** [HvyIndustries/crane#182] opened 2016-10-29 05:04 UTC
It's not working with codeigniter auto-completion .
Do I have to add some additional settings for the framework to work?

**Comment by TheColorRed** [comment] 2016-10-30 00:49
It depends on the code, auto-completion is not 100% built in yet. See #177

**Comment by nevadascout** [comment] 2017-03-04 01:26
Duplicate of #148

**Closed by nevadascout** 2017-03-04 01:26 UTC
