### ISSUE TITLE
Randomly stops during parsing/indexing.

### ISSUE THREAD

**Issue by Arc0re** [HvyIndustries/crane#129] opened 2016-07-21 13:27 UTC
I'm trying to use Crane with a workspace containing various projects and Crane always stops parsing for no reason around 14% (not always, sometimes before and after). I tried with a little project of a hundred of files, its the same.
The debug output doesn't contain any error, it just stops parsing.

My VSCode is up to date, I also have other extensions for PHP such as PHP Debug, PHP Code Format and PHP Symbols. (Maybe there could be a conflict? No idea).
Also, when trying to reindexing, with "Reindex PHP Files in the workspace", it spits an error in the JS debug console:
`channel closed: Error: channel closed`

**Comment by nevadascout** [comment] 2016-08-20 13:00
Hey, thanks for reporting this and I'm sorry this is causing you an issue.

To solve this, I need to know what code is causing the parser to break. Using the debug console, you should be able to figure out which file is causing the problem. Then, if you could share the source code of that file with me that would be a great help.

I believe that the php parser itself is having an issue that completely crashes the entire "server" backend thread which would explain the `channel closed` error message.

**Comment by nevadascout** [comment] 2016-09-24 09:46
We've narrowed down the cause of this to a memory leak in the parser library.

Closing as duplicate of #157

**Closed by nevadascout** 2016-09-24 09:46 UTC
Labels: bug
