### ISSUE TITLE
filePath and item.path never match in SuggestionBuilder

### ISSUE THREAD

**Issue by CarlosAzocar** [HvyIndustries/crane#268] opened 2017-03-19 07:35 UTC
Sorry for my inglish.

I have this problem:

**[Error - 3:14:04] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'classes' of undefined
  Code: -32603** 

Apparently in SuggestionBuilder:

```javascript
 this.currentFileNode = this.workspaceTree.filter(item => {
     console.log(item.path + " --> " + (item.path == this.filePath)); // testing
     return item.path == this.filePath;
 })[0];
```
_item.path and filePath never match_ 

this is "this.filePath":
**c:\Users\Carlos%20Azocar\Desktop\StandardLivesApp\app\Http\Controllers\Controller.php**

C:/Users/Carlos Azocar/AppData/Roaming/Crane/phpstubs/crane-php-stubs-master/apc.php --> false
C:/Users/Carlos Azocar/AppData/Roaming/Crane/phpstubs/crane-php-stubs-master/bcmath.php --> false
C:/Users/Carlos Azocar/AppData/Roaming/Crane/phpstubs/crane-php-stubs-master/basic.php --> false
C:/Users/Carlos Azocar/AppData/Roaming/Crane/phpstubs/crane-php-stubs-master/bz2.php --> false
C:/Users/Carlos Azocar/AppData/Roaming/Crane/phpstubs/crane-php-stubs-master/apcu.php --> false
.
.
.
That should be this, but item.path == this.filePath return false
**c:\Users\Carlos Azocar\Desktop\StandardLivesApp\app\Http\Controllers\Controller.php --> false**
.
.
.
c:\Users\Carlos Azocar\Desktop\StandardLivesApp\app\Http\Controllers\Auth\PasswordController.php --> false
c:\Users\Carlos Azocar\Desktop\StandardLivesApp\app\Http\Controllers\Auth\AuthController.php --> false
c:\Users\Carlos Azocar\Desktop\StandardLivesApp\resources\views\layouts\app.blade.php --> false

this.currentFileNode remains "undefined"

**Comment by ichiriac** [comment] 2017-03-19 08:47
Hi @CarlosAzocar,

Thanks for reporting and investigating, your help is really appreciated :+1: 

This issue is related/duplicate of this issue : https://github.com/HvyIndustries/crane/issues/257

As I've attached together both issues, I will close this one as duplicate. Fell free to continue investigating and comment on issue 257.

**Closed by ichiriac** 2017-03-19 08:48 UTC
Labels: bug, duplicate
